//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMakeForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckForms
    {
        public CheckForms()
        {
            this.CheckResults = new HashSet<CheckResults>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> TouchDate { get; set; }
        public string FormTemplate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<CheckResults> CheckResults { get; set; }
        public virtual Users Users { get; set; }
    }
}
