//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMakeForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckContentCat
    {
        public CheckContentCat()
        {
            this.CheckContents = new HashSet<CheckContents>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<CheckContents> CheckContents { get; set; }
    }
}
