//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMakeForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckContents
    {
        public CheckContents()
        {
            this.CheckPoints = new HashSet<CheckPoints>();
        }
    
        public int Id { get; set; }
        public string ContentName { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual CheckContentCat CheckContentCat { get; set; }
        public virtual ICollection<CheckPoints> CheckPoints { get; set; }
    }
}
