//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMakeForms.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSMSEntities : DbContext
    {
        public DSMSEntities()
            : base("name=DSMSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckContentCat> CheckContentCat { get; set; }
        public virtual DbSet<CheckContents> CheckContents { get; set; }
        public virtual DbSet<CheckCos> CheckCos { get; set; }
        public virtual DbSet<CheckForms> CheckForms { get; set; }
        public virtual DbSet<Checkings> Checkings { get; set; }
        public virtual DbSet<CheckPoints> CheckPoints { get; set; }
        public virtual DbSet<CheckRefRules> CheckRefRules { get; set; }
        public virtual DbSet<CheckResults> CheckResults { get; set; }
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Companys> Companys { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<RefRuleDocs> RefRuleDocs { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
