//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMakeForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provinces
    {
        public Provinces()
        {
            this.Citys = new HashSet<Citys>();
            this.Companys = new HashSet<Companys>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Citys> Citys { get; set; }
        public virtual ICollection<Companys> Companys { get; set; }
    }
}
