//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToMakeForms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.CheckForms = new HashSet<CheckForms>();
            this.CheckResults = new HashSet<CheckResults>();
        }
    
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string Token { get; set; }
        public Nullable<int> Actived { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Setting { get; set; }
        public int UserRoleId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
    
        public virtual ICollection<CheckForms> CheckForms { get; set; }
        public virtual ICollection<CheckResults> CheckResults { get; set; }
        public virtual Companys Companys { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
